### PR TITLE
Generate workload using k6

### PR DESCRIPTION
**Pull request by sacheendra**
When making thousands of requests, the application loses data. For example, user accounts and articles which were present one request ago disappear. Overall, the usual success rate is over 95%.
I think the problem is on the application side as there is literally no request to delete users, but they disappear nonetheless.
Still usable though.
@joe4dev If you could check with 1000 iterations and confirm.

### CODE REVIEW

**Comment by joe4dev** [comment]
yes, I also got 16 errors (vs 920 success using 1000 iterations, hence 64 skips) with status code 422 (unprocessable entity) on the login and articles/.../favorite endpoint:
Screenshot 2021-04-09 at 20 14 21

The error scenarios yield the following k6 log:

```
msg="TypeError: Cannot read property '0' of undefined\n\tat run (file:///apps/realworld-dynamodb-lambda/workload_script.js:527:149(31))\n\tat file:///apps/realworld-dynamodb-lambda/workload_script.js:521:12(95)\n"

msg="{\n  \"errors\": {\n    \"body\": [\n      \"Email not found: [username_1_7@example.com]\"\n    ]\n  }\n}"
```


The error appears at the API gateway and hence probably due to some malformed JSON sent from k6. The root cause might be an erroneous response from a previous request:
Screenshot 2021-04-09 at 20 37 49

**Comment by sacheendra** [comment]
The cannot read property 0 of undefined errors should not occur. I'll look into that.

As for the other error, do you think an earlier malformed request is deleting users!?

**Comment by joe4dev** [comment]
> As for the other error, do you think an earlier malformed request is deleting users!?

I don't think any endpoint can delete users (except for the purgeData one before starting k6).

"Email not found" originates from a failed login request (https://github.com/perfkit/realworld-dynamodb-lambda/blob/master/src/User.js#L80) and is either caused by:
* a) creating multiple users with the same email: However, this seems to be prevented by the `user_index` in k6 and the backend also validates if a user already exists (https://github.com/perfkit/realworld-dynamodb-lambda/blob/master/src/User.js#L38).
* b) Trying to login a user that does not exist: We could verify if the user with that email really exists (didn't notice any create user requests failing though). Update user also shouldn't interfere because it seems to just update the bio (guess that won't change the email).

**Comment by sacheendra** [comment]
The problem is not in API Gateway. Lambda itself returns the 422 error code

**Comment by sacheendra** [comment]
The problem is due to update user. Update user deletes all fields not in update request. :facepalm:

**Comment by sacheendra** [comment]
The login error stuff was a bug in the application code. it is now solved. On to the article not found error.

**Comment by sacheendra** [comment]
The favorites stuff was a problem in workload_script. Fixed that too. Only the out of bounds error remains

**Comment by sacheendra** [comment]
@joe4dev Did you already add xray instrumentation to this app? If yes, i'll add it to k6

**Comment by joe4dev** [comment]
Yes, everything is instrumented (see XRay trace picture above ;).

Thanks a lot @sacheendra , good work 👏 👌

**Comment by joe4dev** [comment]
Tests with 200 and 1000 iterations look good 👍  🎉
Trace correlation works, status codes ok, no errors appeared in traces and (quickchecked) logs as well.

**Pull request merged**
